#!/bin/bash
PREFIX=/usr/local/code-templates

TEMPLATE_DIR=$PREFIX/$1

#Creates a basic skeleton project directory	
if [ -d $TEMPLATE_DIR ]; then
	cp -r $TEMPLATE_DIR/* .
	echo "Project initialized."
else
	echo "Template does not exist."
fi
